// D&B Catalog Games Data will be used together with scripts.js and html.index
const gamesData = [
    {
        id: 1,
        name: "Treasure Quest",
        type: "Jackpot",
        category: "Interactive [Spin]",
        cost: 10.9,
        value: 4,
        jackpot: "1000 tickets",
        description: "A spinning wheel game where timing is key to winning big jackpots.",
        jaysPayout: 60,
        jaysTips: "Wait for the right moment to stop the wheel for maximum tickets.",
        features: ["Spin the Wheel operation", "Low difficulty"],
        imagePath: null
    },
    {
        id: 2,
        name: "Wicked Tuna",
        type: "Reflex",
        category: "Interactive",
        cost: 7.7,
        value: 4,
        jackpot: null,
        description: "Test your fishing skills by reeling in virtual fish using the rod controller.",
        jaysPayout: 50,
        jaysTips: "Use steady movements with the fishing rod for best results.",
        features: ["Fishing rod reeling"],
        imagePath: "Jays-Arcade-Photos/2.jpg"
    },
    {
        id: 3,
        name: "Fruit Ninja",
        type: "Reflex",
        category: "Touchscreen",
        cost: 7.5,
        value: 4,
        jackpot: null,
        description: "Slice virtual fruits by swiping across the touchscreen as quickly as possible.",
        jaysPayout: 72,
        jaysTips: "Focus on combos for maximum points and tickets.",
        features: ["Touchscreen slicing", "Low difficulty"],
        imagePath: "Jays-Arcade-Photos/3.jpg"
    },
    {
        id: 4,
        name: "Monopoly",
        type: "Jackpot",
        category: "Interactive [Spin]",
        cost: 7.5,
        value: 3,
        jackpot: "2000 tickets",
        description: "Based on the classic board game, spin the dice and advance around the virtual Monopoly board.",
        jaysPayout: 16,
        jaysTips: "The jackpot builds up over time, so playing after others have played might increase your chances.",
        features: ["Spinnable dice", "High difficulty"],
        imagePath: null
    },
    {
        id: 5,
        name: "Crazy Curves",
        type: "Jackpot",
        category: "Timing",
        cost: 7.5,
        value: 3,
        jackpot: "560 tickets",
        description: "Stop the light at the right moment to win big ticket prizes.",
        jaysPayout: 30,
        jaysTips: "Wait for the green light and time your button press carefully.",
        features: ["Stop on the light when it turns green", "High difficulty"],
        imagePath: null
    },
    {
        id: 6,
        name: "Pop It & Wind",
        type: "Jackpot",
        category: "Timing",
        cost: 6.1,
        value: 2,
        jackpot: "260 tickets",
        description: "Time your button press to stop the light at the right spot for instant pop winnings.",
        jaysPayout: 8,
        jaysTips: "Practice your timing and be patient for the best results.",
        features: ["Buzzsaw light timing game", "High difficulty"],
        imagePath: null
    },
    {
        id: 7,
        name: "Pacman Chomp Mania",
        type: "Arcade",
        category: "Button Joystick",
        cost: 6.6,
        value: 3,
        jackpot: "1000 tickets",
        description: "Classic Pacman gameplay with a twist - you only have one life to complete the entire board.",
        jaysPayout: 0,
        jaysTips: "Plan your routes carefully and avoid ghosts at all costs - you only have one life!",
        features: ["Only one life to complete entire board", "Classic Pacman gameplay"],
        imagePath: null
    },
    {
        id: 8,
        name: "Grand Piano Keys",
        type: "Music",
        category: "Interactive",
        cost: 7.5,
        value: 4,
        jackpot: null,
        description: "Test your musical skills on a giant piano keyboard with hand-sized keys.",
        jaysPayout: 58,
        jaysTips: "Be absolutely sure when you press a key because a missed key slows you down significantly.",
        features: ["Big piano keys the size of your hand", "Medium difficulty"],
        imagePath: null
    },
    {
        id: 9,
        name: "Kung Fu Panda Dojo Mojo",
        type: "Reflex",
        category: "Interactive",
        cost: 10.9,
        value: 3,
        jackpot: null,
        description: "Help Po master kung fu by hitting the big buttons at the right time.",
        jaysPayout: 40,
        jaysTips: "Focus on timing your hits with the button prompts for maximum points.",
        features: ["Big buttons", "Low difficulty"],
        imagePath: null
    },
    {
        id: 10,
        name: "Guitar Hero",
        type: "Music",
        category: "Interactive",
        cost: 7.7,
        value: 4,
        jackpot: null,
        description: "Play along to popular songs using the guitar-shaped controller.",
        jaysPayout: 0,
        jaysTips: "Practice makes perfect - start with easier songs and work your way up.",
        features: ["Guitar shaped control", "Medium difficulty"],
        imagePath: "Jays-Arcade-Photos/10.jpg"
    },
    {
        id: 11,
        name: "Floppy Tickets",
        type: "Reflex",
        category: "Push A Button",
        cost: 7.5,
        value: 3,
        jackpot: "250 tickets",
        description: "Press the button at the right time to win tickets.",
        jaysPayout: 32,
        jaysTips: "Focus on the timing pattern to maximize your winnings.",
        features: ["Button timing", "Low difficulty"],
        imagePath: null
    },
    {
        id: 12,
        name: "Crossy Road",
        type: "Reflex",
        category: "Push A Button",
        cost: 7.5,
        value: 4,
        jackpot: "250 tickets",
        description: "Based on the popular mobile game, help your character cross busy roads and obstacles.",
        jaysPayout: 84,
        jaysTips: "Patience is key - wait for the right moment to cross safely.",
        features: ["Button timing", "Low difficulty"],
        imagePath: null
    },
    {
        id: 13,
        name: "Jurassic World Fallen Kingdom",
        type: "Jackpot",
        category: "Restraint",
        cost: 7.7,
        value: 4,
        jackpot: "530 tickets",
        description: "Push a jeep with just the right amount of force to win big tickets.",
        jaysPayout: 70,
        jaysTips: "Use controlled force - too little won't move it, too much will push it too far.",
        features: ["Push a jeep", "High difficulty"],
        imagePath: "Jays-Arcade-Photos/13.jpg"
    },
    {
        id: 14,
        name: "Break the Plate",
        type: "Jackpot",
        category: "Interactive [Throwing]",
        cost: 7.7,
        value: 4,
        jackpot: "282 tickets",
        description: "Throw rubber balls to break virtual plates and win tickets.",
        jaysPayout: 97,
        jaysTips: "Aim for the center of the plates for the most consistent breaks.",
        features: ["Throwing rubber balls", "Medium difficulty"],
        imagePath: "Jays-Arcade-Photos/14.jpg"
    },
    {
        id: 15,
        name: "Lets Bounce",
        type: "Jackpot",
        category: "Interactive [Throwing]",
        cost: 7.5,
        value: 3,
        jackpot: null,
        description: "Throw ping pong balls into targets to win tickets.",
        jaysPayout: 20,
        jaysTips: "Use a gentle arc when throwing for the best results.",
        features: ["Throw ping pong balls", "Medium difficulty"],
        imagePath: "Jays-Arcade-Photos/15.jpg"
    },
    {
        id: 16,
        name: "Tailgate Toss",
        type: "Jackpot",
        category: "Interactive [Throwing]",
        cost: 7.5,
        value: 3,
        jackpot: "500 tickets",
        description: "Toss balls into holes of different point values, similar to cornhole/bean bag toss.",
        jaysPayout: 16,
        jaysTips: "Aim for the high-value center holes. The ticket payout scales with your score.",
        features: ["Bean bag toss", "Medium difficulty"],
        imagePath: "Jays-Arcade-Photos/16.jpg"
    },
    {
        id: 17,
        name: "Super Bikes 3",
        type: "Racing",
        category: "Interactive [Driving]",
        cost: 7.5,
        value: 4,
        jackpot: null,
        description: "Experience the thrill of motorcycle racing with realistic motion controls.",
        jaysPayout: 0,
        jaysTips: "Lean into turns for better handling and faster lap times.",
        features: ["Riding a Motorcycle", "Medium difficulty"],
        imagePath: "Jays-Arcade-Photos/17.jpg"
    },
    {
        id: 18,
        name: "Minecraft Dungeons Arcade",
        type: "Arcade",
        category: "Button Joystick",
        cost: 8.8,
        value: 4,
        jackpot: null,
        description: "Explore the blocky world of Minecraft in this arcade adaptation of Minecraft Dungeons.",
        jaysPayout: 0,
        jaysTips: "Collect power-ups and work together with other players for the best experience.",
        features: ["Minecraft-themed adventure", "Multiplayer gameplay"],
        imagePath: null
    },
    {
        id: 19,
        name: "Cruisin Blast",
        type: "Racing",
        category: "Interactive [Driving]",
        cost: 7.5,
        value: 4,
        jackpot: null,
        description: "Fast-paced racing game with exotic cars and extreme environments.",
        jaysPayout: 0,
        jaysTips: "Use drift mechanics for speed boosts around corners.",
        features: ["Exotic cars", "Extreme environments"],
        imagePath: "Jays-Arcade-Photos/19.jpg"
    },
    {
        id: 20,
        name: "Mariokart Arcade GP",
        type: "Racing",
        category: "Interactive [Driving]",
        cost: 7.5,
        value: 5,
        jackpot: null,
        description: "Race as Mario characters on various tracks with power-ups and special items.",
        jaysPayout: 0,
        jaysTips: "Use items strategically and master the drift boost for best results.",
        features: ["Nintendo characters", "Power-up items"],
        imagePath: "Jays-Arcade-Photos/20.jpg"
    },
    {
        id: 21,
        name: "Alien Covenant",
        type: "Survival",
        category: "Interactive [Shooting]",
        cost: 7.5,
        value: 4,
        jackpot: null,
        description: "Intense shooter based on the Alien franchise where you must survive xenomorph attacks.",
        jaysPayout: 0,
        jaysTips: "Conserve ammo and aim for headshots for maximum effectiveness.",
        features: ["Alien franchise", "Horror shooter"],
        imagePath: "Jays-Arcade-Photos/21.jpg"
    },
    {
        id: 22,
        name: "The Walking Dead",
        type: "Survival",
        category: "Interactive [Throwing]",
        cost: 7.5,
        value: 4,
        jackpot: null,
        description: "Zombie shooter game based on the popular TV series.",
        jaysPayout: 0,
        jaysTips: "Focus on headshots and watch for special zombies that require multiple hits.",
        features: ["TV series theme", "Zombie apocalypse"],
        imagePath: "Jays-Arcade-Photos/22.jpg"
    },
    {
        id: 23,
        name: "Connect 4 Hoops",
        type: "Sports",
        category: "Interactive [Throwing]",
        cost: 8.8,
        value: 4,
        jackpot: null,
        description: "Basketball version of Connect 4. Sink baskets to drop your colored tokens and create patterns.",
        jaysPayout: 0,
        jaysTips: "Aim for the middle hoops first to control the board better.",
        features: ["Basketball skill", "Strategic gameplay"],
        imagePath: "Jays-Arcade-Photos/23.jpg"
    },
    {
        id: 24,
        name: "Dodgeball Ultimate Arena",
        type: "Sports",
        category: "Interactive [Throwing]",
        cost: 8.8,
        value: 3,
        jackpot: null,
        description: "Test your dodgeball skills in this fast-paced arcade version of the classic game.",
        jaysPayout: 0,
        jaysTips: "Aim carefully and time your throws to catch opponents off guard.",
        features: ["Throwing skill", "Dodging mechanics"],
        imagePath: null
    },
    {
        id: 25,
        name: "Frogger",
        type: "Strategy",
        category: "Push A Button",
        cost: 5.4,
        value: 3,
        jackpot: null,
        description: "Classic arcade game where you guide a frog across a busy road and river.",
        jaysPayout: 2,
        jaysTips: "Patience is key - wait for safe openings rather than rushing across.",
        features: ["Classic arcade game", "Timing-based gameplay"],
        imagePath: "Jays-Arcade-Photos/25.jpg"
    },
    {
        id: 26,
        name: "Deal or No Deal",
        type: "Strategy",
        category: "Push A Button",
        cost: 8.7,
        value: 4,
        jackpot: "250 tickets",
        description: "Based on the TV show, pick cases and decide whether to accept offers for tickets.",
        jaysPayout: 8,
        jaysTips: "If offered more than 60% of the highest remaining case value, usually take it.",
        features: ["TV show theme", "Basketball", "High difficulty"],
        imagePath: "Jays-Arcade-Photos/26.jpg"
    },
    {
        id: 27,
        name: "Zombie",
        type: "Reflex",
        category: "Push A Button",
        cost: 7.5,
        value: 3,
        jackpot: "780 tickets",
        description: "Survive a zombie apocalypse by pressing buttons at the right time.",
        jaysPayout: 2,
        jaysTips: "Focus on the timing patterns to maximize your survival chances.",
        features: ["Button timing", "High difficulty"],
        imagePath: "Jays-Arcade-Photos/27.jpg"
    },
    {
        id: 28,
        name: "Hatchet Hero",
        type: "Sports",
        category: "Interactive [Throwing]",
        cost: 6.6,
        value: 3,
        jackpot: null,
        description: "Test your axe-throwing skills in this carnival-style arcade game.",
        jaysPayout: 0,
        jaysTips: "Focus on consistent throwing motion for the best accuracy.",
        features: ["Axe throwing simulation", "Skill-based gameplay"],
        imagePath: "Jays-Arcade-Photos/28.jpg"
    },
    {
        id: 29,
        name: "Baseball Pro",
        type: "Sports",
        category: "Timing",
        cost: 7.5,
        value: 4,
        jackpot: "1000 tickets",
        description: "Test your baseball batting skills with realistic timing mechanics.",
        jaysPayout: 60,
        jaysTips: "Watch the pitcher's movements carefully and time your swing perfectly.",
        features: ["Baseball", "Low difficulty"],
        imagePath: null
    },
    {
        id: 30,
        name: "2 Minute Drill",
        type: "Sports",
        category: "Interactive [Throwing]",
        cost: 6.1,
        value: 3,
        jackpot: "250 tickets",
        description: "Test your football throwing accuracy within a two-minute time limit.",
        jaysPayout: 0,
        jaysTips: "Aim carefully and establish a rhythm for the best results.",
        features: ["Football", "Timed challenge"],
        imagePath: null
    },
    {
        id: 31,
        name: "Galaga Assault",
        type: "Arcade",
        category: "Button Joystick",
        cost: 6.6,
        value: 3,
        jackpot: null,
        description: "Modern version of the classic space shooter with enhanced graphics and new enemy patterns.",
        jaysPayout: 0,
        jaysTips: "Save your special weapons for boss encounters and large enemy waves.",
        features: ["Classic arcade shooter", "Enhanced graphics"],
        imagePath: null
    },
    {
        id: 32,
        name: "Candy Crush Saga",
        type: "Strategy",
        category: "Touchscreen",
        cost: 8.8,
        value: 2,
        jackpot: null,
        description: "Based on the popular mobile game, match candies to earn tickets.",
        jaysPayout: 12,
        jaysTips: "Focus on creating special candy combinations for maximum points.",
        features: ["Touchscreen matching", "Mobile game adaptation"],
        imagePath: null
    },
    {
        id: 33,
        name: "Wack n Win",
        type: "Arcade",
        category: "Interactive",
        cost: 6.0,
        value: 3,
        jackpot: "200 tickets",
        description: "Whack targets as they appear to win tickets in this reflexive game.",
        jaysPayout: 15,
        jaysTips: "Focus on speed and accuracy for the highest scores.",
        features: ["Whack-a-mole style", "Fast reflexes required"],
        imagePath: "Jays-Arcade-Photos/33.jpg"
    }
];